post_install() {
    if [ -f /etc/plymouth/plymouthd.conf ]; then
        if grep -q "^Theme=" /etc/plymouth/plymouthd.conf; then
            sed -i 's/^Theme=.*/Theme=bakeryos/g' /etc/plymouth/plymouthd.conf
        else
            sed -i '/\[Daemon\]/a Theme=bakeryos' /etc/plymouth/plymouthd.conf
        fi
    else
        echo -e "[Daemon]\nTheme=bakeryos" > /etc/plymouth/plymouthd.conf
    fi
}

post_upgrade() {
    post_install
}